version: '3.8'

services:
  web:
    image: taipy-app
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=aws-0-eu-central-1.pooler.supabase.com  # Korrekte externe Adresse!
      - DB_PORT=6543
      - DB_NAME=postgres
      - DB_USER=postgres.dvgannvtzcvqnpdxrvno
      - DB_PASSWORD=w5b^b4XmNfAo7v  # ⚠️ Optional in `.env` auslagern!

    # depends_on:
    #   db:
    #     condition: service_healthy

  # db:
  #   image: postgres:16
  #   environment:
  #     POSTGRES_USER: postgres.dvgannvtzcvqnpdxrvno
  #     POSTGRES_PASSWORD: w5b^b4XmNfAo7v
  #     POSTGRES_DB: postgres
  #   ports:
  #     - "6543:6543"
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
  #     interval: 5s
  #     retries: 5
  #     start_period: 10s