version: '3.8'

services:
  web:
    image: taipy-app
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=dpg-cuke2v5umphs73bcnhu0-a.a.render.com      # Externer Host für Render-Datenbank
      - DB_PORT=5432
      - DB_NAME=adl_data
      - DB_USER=adl_data_user
      - DB_PASSWORD=6YpiBm5BJCR6ABi9IELdCN9MqXLcGvIF         # Dein Passwort aus Render
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jD5rb#qojM4Ki%
      POSTGRES_DB: adl_data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d adl_data"]
      interval: 5s
      retries: 5
      start_period: 10s

