"""widen player position to 10 chars

Revision ID: 08db7025a178
Revises: 1c7b0c814359
Create Date: 2026-03-10 16:40:18.790052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08db7025a178'
down_revision: Union[str, Sequence[str], None] = '1c7b0c814359'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'position',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=10),
               comment='Position: QB, RB, WR, TE, PK, PN, DT, DE, LB, CB, S, Coach, TMQB, etc.',
               existing_comment='Position: QB, RB, WR, TE, PK, PN, DT, DE, LB, CB, S, TMQB, etc.',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'position',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=4),
               comment='Position: QB, RB, WR, TE, PK, PN, DT, DE, LB, CB, S, TMQB, etc.',
               existing_comment='Position: QB, RB, WR, TE, PK, PN, DT, DE, LB, CB, S, Coach, TMQB, etc.',
               existing_nullable=False)
    # ### end Alembic commands ###
