"""widen player position to 4 chars

Revision ID: 1c7b0c814359
Revises: 7e91d92108de
Create Date: 2026-03-10 16:38:41.517859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c7b0c814359'
down_revision: Union[str, Sequence[str], None] = '7e91d92108de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'position',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=4),
               comment='Position: QB, RB, WR, TE, PK, PN, DT, DE, LB, CB, S, TMQB, etc.',
               existing_comment='Position: QB, RB, WR, TE, PK, PN, DT, DE, LB, CB, S',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'position',
               existing_type=sa.String(length=4),
               type_=sa.VARCHAR(length=3),
               comment='Position: QB, RB, WR, TE, PK, PN, DT, DE, LB, CB, S',
               existing_comment='Position: QB, RB, WR, TE, PK, PN, DT, DE, LB, CB, S, TMQB, etc.',
               existing_nullable=False)
    # ### end Alembic commands ###
