"""add season_calendar table

Revision ID: 48ff388fedeb
Revises: a3f7e2c91d4b
Create Date: 2026-03-12 11:21:45.249235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48ff388fedeb'
down_revision: Union[str, Sequence[str], None] = 'a3f7e2c91d4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('season_calendars',
    sa.Column('season', sa.Integer(), nullable=False, comment='ADL season year, e.g. 2026'),
    sa.Column('oext_deadline', sa.Date(), nullable=True, comment='Offseason extension window close'),
    sa.Column('tag_deadline', sa.Date(), nullable=True, comment='Franchise tag declaration deadline'),
    sa.Column('tender_deadline', sa.Date(), nullable=True, comment='RFA/ERFA tender declaration deadline'),
    sa.Column('br_deadline', sa.Date(), nullable=True, comment='Buyout/Restructure declaration deadline'),
    sa.Column('fyo_deadline', sa.Date(), nullable=True, comment='5th Year Option exercise deadline'),
    sa.Column('rookie_signing_deadline', sa.Date(), nullable=True, comment='Unsigned rookies auto-sign deadline'),
    sa.Column('salary_rankings_date', sa.Date(), nullable=True, comment='Jul 1 salary rankings published'),
    sa.Column('rf_auction_start', sa.Date(), nullable=True, comment='Reserve/Futures auction start'),
    sa.Column('rf_auction_end', sa.Date(), nullable=True, comment='Reserve/Futures auction end'),
    sa.Column('ft_auction_start', sa.Date(), nullable=True, comment='Franchise Tag auction start'),
    sa.Column('ft_auction_end', sa.Date(), nullable=True, comment='Franchise Tag auction end'),
    sa.Column('rfa_auction_start', sa.Date(), nullable=True, comment='Restricted Free Agent auction start'),
    sa.Column('rfa_auction_end', sa.Date(), nullable=True, comment='Restricted Free Agent auction end'),
    sa.Column('br_auction_start', sa.Date(), nullable=True, comment='Buyout/Restructure auction start'),
    sa.Column('br_auction_end', sa.Date(), nullable=True, comment='Buyout/Restructure auction end'),
    sa.Column('rookie_draft_start', sa.Date(), nullable=True, comment='ADL Rookie Draft start'),
    sa.Column('rookie_draft_end', sa.Date(), nullable=True, comment='ADL Rookie Draft end'),
    sa.Column('udfa_auction_start', sa.Date(), nullable=True, comment='UDFA auction start'),
    sa.Column('udfa_auction_end', sa.Date(), nullable=True, comment='UDFA auction end'),
    sa.Column('ufa_auction_start', sa.Date(), nullable=True, comment='UFA auction open (continuous through season)'),
    sa.Column('iext_window_start', sa.Date(), nullable=True, comment='In-season extension window start'),
    sa.Column('iext_window_end', sa.Date(), nullable=True, comment='In-season extension window end'),
    sa.Column('regular_season_start', sa.Date(), nullable=True, comment='NFL regular season start (Week 1)'),
    sa.Column('regular_season_end', sa.Date(), nullable=True, comment='NFL regular season end (Week 18)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', name='uq_season_calendar_season')
    )
    op.create_index(op.f('ix_season_calendars_season'), 'season_calendars', ['season'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_season_calendars_season'), table_name='season_calendars')
    op.drop_table('season_calendars')
    # ### end Alembic commands ###
