"""add player_scores table

Revision ID: 7e91d92108de
Revises: 827bb2529fb6
Create Date: 2026-03-10 16:20:19.329921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e91d92108de'
down_revision: Union[str, Sequence[str], None] = '827bb2529fb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_scores',
    sa.Column('player_id', sa.Integer(), nullable=False, comment='FK to players.id'),
    sa.Column('season', sa.Integer(), nullable=False, comment='ADL season year'),
    sa.Column('week', sa.String(length=3), nullable=False, comment="'YTD' for season totals, '1'-'17' for weekly"),
    sa.Column('points', sa.Numeric(precision=7, scale=2), nullable=False, comment='Fantasy points scored'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season', 'week', name='uq_player_score_player_season_week')
    )
    op.create_index(op.f('ix_player_scores_player_id'), 'player_scores', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_scores_player_id'), table_name='player_scores')
    op.drop_table('player_scores')
    # ### end Alembic commands ###
