"""initial schema

Revision ID: 827bb2529fb6
Revises: 
Create Date: 2026-03-10 14:56:12.159915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '827bb2529fb6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('mfl_id', sa.Integer(), nullable=False, comment='MFL player ID (external identifier)'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Display name'),
    sa.Column('position', sa.String(length=3), nullable=False, comment='Position: QB, RB, WR, TE, PK, PN, DT, DE, LB, CB, S'),
    sa.Column('nfl_team', sa.String(length=3), nullable=True, comment='3-letter NFL team code, null for free agents'),
    sa.Column('birthdate', sa.Date(), nullable=True, comment='Player birthdate'),
    sa.Column('draft_year', sa.Integer(), nullable=True, comment='NFL draft year'),
    sa.Column('draft_round', sa.Integer(), nullable=True, comment='NFL draft round'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_mfl_id'), 'players', ['mfl_id'], unique=True)
    op.create_table('teams',
    sa.Column('franchise_id', sa.String(length=4), nullable=False, comment="MFL franchise ID, e.g. '0001'"),
    sa.Column('name', sa.String(length=100), nullable=False, comment='ADL team name'),
    sa.Column('conference', sa.String(length=3), nullable=False, comment='AFC or NFC'),
    sa.Column('division', sa.String(length=50), nullable=False, comment='Division name'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_franchise_id'), 'teams', ['franchise_id'], unique=True)
    op.create_table('contracts',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False, comment='ADL season year this contract is for'),
    sa.Column('salary', sa.Numeric(precision=5, scale=2), nullable=False, comment='Salary in millions, e.g. 10.07 = $10.07M'),
    sa.Column('years_remaining', sa.Integer(), nullable=False, comment='Contract years left including current season'),
    sa.Column('contract_type', sa.String(length=2), nullable=False, comment='NG, SD, or FG — determines cap penalty'),
    sa.Column('designation', sa.String(length=50), nullable=False, comment="Contract info string: '2019 EXT', '2021 1.02', '2021 UFA', etc."),
    sa.Column('status', sa.String(length=20), nullable=False, comment='active, expired, bought_out, traded'),
    sa.Column('signed_season', sa.Integer(), nullable=False, comment='Season the original contract was signed'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'player_id', 'season', name='uq_contract_team_player_season')
    )
    op.create_index(op.f('ix_contracts_player_id'), 'contracts', ['player_id'], unique=False)
    op.create_index(op.f('ix_contracts_team_id'), 'contracts', ['team_id'], unique=False)
    op.create_table('draft_picks',
    sa.Column('season', sa.Integer(), nullable=False, comment='Draft year'),
    sa.Column('round', sa.Integer(), nullable=False, comment='Round 1-5'),
    sa.Column('pick', sa.Integer(), nullable=False, comment='Pick number within round'),
    sa.Column('original_team_id', sa.Integer(), nullable=False, comment='Team that originally owned the pick'),
    sa.Column('current_team_id', sa.Integer(), nullable=False, comment='Team that currently owns the pick'),
    sa.Column('player_id', sa.Integer(), nullable=True, comment='Player selected — null until pick is used'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['current_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['original_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', 'round', 'pick', name='uq_draft_pick_season_round_pick')
    )
    op.create_index(op.f('ix_draft_picks_current_team_id'), 'draft_picks', ['current_team_id'], unique=False)
    op.create_index(op.f('ix_draft_picks_original_team_id'), 'draft_picks', ['original_team_id'], unique=False)
    op.create_index(op.f('ix_draft_picks_player_id'), 'draft_picks', ['player_id'], unique=False)
    op.create_table('salary_cap_snapshots',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False, comment='ADL season year'),
    sa.Column('week', sa.Integer(), nullable=False, comment='Snapshot week: 3, 7, 11, or 16'),
    sa.Column('total_salary', sa.Numeric(precision=6, scale=2), nullable=False, comment='Total salary expenditures in millions'),
    sa.Column('cap_penalties', sa.Numeric(precision=6, scale=2), nullable=False, comment='Cap penalties in millions'),
    sa.Column('cap_space', sa.Numeric(precision=6, scale=2), nullable=False, comment='Remaining cap space in millions'),
    sa.Column('salary_cap', sa.Numeric(precision=6, scale=2), nullable=False, comment='Franchise salary cap for the season in millions'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'season', 'week', name='uq_cap_snapshot_team_season_week')
    )
    op.create_index(op.f('ix_salary_cap_snapshots_team_id'), 'salary_cap_snapshots', ['team_id'], unique=False)
    op.create_table('transactions',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True, comment='Null for pick-only transactions'),
    sa.Column('transaction_type', sa.String(length=20), nullable=False, comment='Type of transaction'),
    sa.Column('season', sa.Integer(), nullable=False, comment='ADL season year'),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Transaction-specific data'),
    sa.Column('executed_at', sa.DateTime(), nullable=False, comment='When the transaction was executed'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_player_id'), 'transactions', ['player_id'], unique=False)
    op.create_index(op.f('ix_transactions_team_id'), 'transactions', ['team_id'], unique=False)
    op.create_table('roster_entries',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=False, comment='ADL season year'),
    sa.Column('roster_status', sa.String(length=20), nullable=False, comment='ROSTER, INJURED_RESERVE, or TAXI_SQUAD'),
    sa.Column('acquired_date', sa.DateTime(), nullable=True, comment='When player was added to this roster'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season', name='uq_roster_player_season')
    )
    op.create_index(op.f('ix_roster_entries_contract_id'), 'roster_entries', ['contract_id'], unique=False)
    op.create_index(op.f('ix_roster_entries_player_id'), 'roster_entries', ['player_id'], unique=False)
    op.create_index(op.f('ix_roster_entries_team_id'), 'roster_entries', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roster_entries_team_id'), table_name='roster_entries')
    op.drop_index(op.f('ix_roster_entries_player_id'), table_name='roster_entries')
    op.drop_index(op.f('ix_roster_entries_contract_id'), table_name='roster_entries')
    op.drop_table('roster_entries')
    op.drop_index(op.f('ix_transactions_team_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_player_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_salary_cap_snapshots_team_id'), table_name='salary_cap_snapshots')
    op.drop_table('salary_cap_snapshots')
    op.drop_index(op.f('ix_draft_picks_player_id'), table_name='draft_picks')
    op.drop_index(op.f('ix_draft_picks_original_team_id'), table_name='draft_picks')
    op.drop_index(op.f('ix_draft_picks_current_team_id'), table_name='draft_picks')
    op.drop_table('draft_picks')
    op.drop_index(op.f('ix_contracts_team_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_player_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_teams_franchise_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_players_mfl_id'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
