"""add player_seasons table

Revision ID: b23f30ecfda0
Revises: 48ff388fedeb
Create Date: 2026-04-02 20:02:00.228293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b23f30ecfda0'
down_revision: Union[str, Sequence[str], None] = '48ff388fedeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('season_calendars', 'season',
               existing_type=sa.INTEGER(),
               comment='ADL season year',
               existing_comment='ADL season year, e.g. 2026',
               existing_nullable=False)
    op.alter_column('season_calendars', 'tag_deadline',
               existing_type=sa.DATE(),
               comment='Franchise tag deadline',
               existing_comment='Franchise tag declaration deadline',
               existing_nullable=True)
    op.alter_column('season_calendars', 'tender_deadline',
               existing_type=sa.DATE(),
               comment='RFA/ERFA tender deadline',
               existing_comment='RFA/ERFA tender declaration deadline',
               existing_nullable=True)
    op.alter_column('season_calendars', 'br_deadline',
               existing_type=sa.DATE(),
               comment='Buyout/Restructure deadline',
               existing_comment='Buyout/Restructure declaration deadline',
               existing_nullable=True)
    op.alter_column('season_calendars', 'fyo_deadline',
               existing_type=sa.DATE(),
               comment='5th Year Option deadline',
               existing_comment='5th Year Option exercise deadline',
               existing_nullable=True)
    op.alter_column('season_calendars', 'rookie_signing_deadline',
               existing_type=sa.DATE(),
               comment='Unsigned rookies auto-sign',
               existing_comment='Unsigned rookies auto-sign deadline',
               existing_nullable=True)
    op.alter_column('season_calendars', 'rfa_auction_start',
               existing_type=sa.DATE(),
               comment='RFA auction start',
               existing_comment='Restricted Free Agent auction start',
               existing_nullable=True)
    op.alter_column('season_calendars', 'rfa_auction_end',
               existing_type=sa.DATE(),
               comment='RFA auction end',
               existing_comment='Restricted Free Agent auction end',
               existing_nullable=True)
    op.alter_column('season_calendars', 'ufa_auction_start',
               existing_type=sa.DATE(),
               comment='UFA auction open (continuous)',
               existing_comment='UFA auction open (continuous through season)',
               existing_nullable=True)
    op.alter_column('season_calendars', 'regular_season_start',
               existing_type=sa.DATE(),
               comment='NFL regular season start',
               existing_comment='NFL regular season start (Week 1)',
               existing_nullable=True)
    op.alter_column('season_calendars', 'regular_season_end',
               existing_type=sa.DATE(),
               comment='NFL regular season end',
               existing_comment='NFL regular season end (Week 18)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('season_calendars', 'regular_season_end',
               existing_type=sa.DATE(),
               comment='NFL regular season end (Week 18)',
               existing_comment='NFL regular season end',
               existing_nullable=True)
    op.alter_column('season_calendars', 'regular_season_start',
               existing_type=sa.DATE(),
               comment='NFL regular season start (Week 1)',
               existing_comment='NFL regular season start',
               existing_nullable=True)
    op.alter_column('season_calendars', 'ufa_auction_start',
               existing_type=sa.DATE(),
               comment='UFA auction open (continuous through season)',
               existing_comment='UFA auction open (continuous)',
               existing_nullable=True)
    op.alter_column('season_calendars', 'rfa_auction_end',
               existing_type=sa.DATE(),
               comment='Restricted Free Agent auction end',
               existing_comment='RFA auction end',
               existing_nullable=True)
    op.alter_column('season_calendars', 'rfa_auction_start',
               existing_type=sa.DATE(),
               comment='Restricted Free Agent auction start',
               existing_comment='RFA auction start',
               existing_nullable=True)
    op.alter_column('season_calendars', 'rookie_signing_deadline',
               existing_type=sa.DATE(),
               comment='Unsigned rookies auto-sign deadline',
               existing_comment='Unsigned rookies auto-sign',
               existing_nullable=True)
    op.alter_column('season_calendars', 'fyo_deadline',
               existing_type=sa.DATE(),
               comment='5th Year Option exercise deadline',
               existing_comment='5th Year Option deadline',
               existing_nullable=True)
    op.alter_column('season_calendars', 'br_deadline',
               existing_type=sa.DATE(),
               comment='Buyout/Restructure declaration deadline',
               existing_comment='Buyout/Restructure deadline',
               existing_nullable=True)
    op.alter_column('season_calendars', 'tender_deadline',
               existing_type=sa.DATE(),
               comment='RFA/ERFA tender declaration deadline',
               existing_comment='RFA/ERFA tender deadline',
               existing_nullable=True)
    op.alter_column('season_calendars', 'tag_deadline',
               existing_type=sa.DATE(),
               comment='Franchise tag declaration deadline',
               existing_comment='Franchise tag deadline',
               existing_nullable=True)
    op.alter_column('season_calendars', 'season',
               existing_type=sa.INTEGER(),
               comment='ADL season year, e.g. 2026',
               existing_comment='ADL season year',
               existing_nullable=False)
    # ### end Alembic commands ###
